# Generated by Django 4.2 on 2026-06-12 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='资产编号')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='资产名称')),
                ('asset_type', models.CharField(choices=[('server', '服务器'), ('pc', 'PC'), ('printer', '打印机'), ('network_device', '网络设备'), ('switch', '交换机'), ('software', '软件'), ('consumable', '耗材')], db_index=True, max_length=20, verbose_name='资产类型')),
                ('brand', models.CharField(blank=True, default='', max_length=100, verbose_name='品牌')),
                ('spec_model', models.CharField(blank=True, default='', max_length=200, verbose_name='规格型号')),
                ('serial_number', models.CharField(blank=True, default='', max_length=200, verbose_name='序列号/SN码')),
                ('nc_number', models.CharField(blank=True, default='', max_length=50, verbose_name='NC编号')),
                ('status', models.CharField(choices=[('in_stock', '在库'), ('in_use', '在用'), ('borrowed', '借用'), ('repair', '维修'), ('scrapped', '报废'), ('transferring', '调拨中')], db_index=True, default='in_stock', max_length=20, verbose_name='资产状态')),
                ('responsible_person', models.CharField(blank=True, default='', max_length=50, verbose_name='责任人')),
                ('room_name', models.CharField(blank=True, default='', max_length=100, verbose_name='机房名称')),
                ('cabinet_no', models.CharField(blank=True, default='', max_length=50, verbose_name='机柜编号')),
                ('storage_location', models.CharField(blank=True, default='', max_length=200, verbose_name='存放位置描述')),
                ('remarks', models.TextField(blank=True, default='', verbose_name='备注')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='购置日期')),
                ('production_date', models.DateField(blank=True, null=True, verbose_name='生产日期')),
                ('purchase_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='购置金额(元)')),
                ('depreciation_years', models.IntegerField(blank=True, null=True, verbose_name='折旧年限')),
                ('warranty_expiry', models.DateField(blank=True, null=True, verbose_name='保修截止日期')),
                ('warranty_status', models.CharField(blank=True, choices=[('under_warranty', '在保'), ('expired', '过保')], default='', max_length=20, verbose_name='保修状态')),
                ('cpu_model', models.CharField(blank=True, default='', max_length=200, verbose_name='CPU型号')),
                ('memory_info', models.CharField(blank=True, default='', max_length=100, verbose_name='内存')),
                ('disk_size', models.CharField(blank=True, default='', max_length=200, verbose_name='硬盘')),
                ('os', models.CharField(blank=True, default='', max_length=100, verbose_name='操作系统')),
                ('has_monitor', models.BooleanField(blank=True, null=True, verbose_name='是否带显示器')),
                ('monitor_model', models.CharField(blank=True, default='', max_length=200, verbose_name='显示器型号')),
                ('oob_address', models.CharField(blank=True, default='', max_length=100, verbose_name='管理地址(OOB)')),
                ('nic_info', models.TextField(blank=True, default='', verbose_name='网卡信息')),
                ('ip_address', models.CharField(blank=True, default='', max_length=100, verbose_name='IP地址/管理地址')),
                ('mac_address', models.CharField(blank=True, default='', max_length=50, verbose_name='MAC地址')),
                ('port_count', models.IntegerField(blank=True, null=True, verbose_name='端口数量')),
                ('firmware', models.CharField(blank=True, default='', max_length=100, verbose_name='固件版本')),
                ('printer_type', models.CharField(blank=True, choices=[('laser', '激光'), ('inkjet', '喷墨'), ('dot_matrix', '针式'), ('mfp', '多功能一体机')], default='', max_length=20, verbose_name='打印机类型')),
                ('is_color', models.BooleanField(blank=True, null=True, verbose_name='是否彩色')),
                ('is_duplex', models.BooleanField(blank=True, null=True, verbose_name='是否双面打印')),
                ('connect_type', models.CharField(blank=True, choices=[('usb', 'USB'), ('wired', '有线网络'), ('wifi', 'WiFi')], default='', max_length=20, verbose_name='连接方式')),
                ('cartridge_model', models.CharField(blank=True, default='', max_length=200, verbose_name='硒鼓/墨盒型号')),
                ('network_type', models.CharField(blank=True, choices=[('router', '路由器'), ('firewall', '防火墙'), ('switch_dev', '交换机'), ('load_balancer', '负载均衡'), ('wireless_controller', '无线控制器'), ('vpn_gateway', 'VPN网关')], default='', max_length=30, verbose_name='网络设备类型')),
                ('port_type', models.CharField(blank=True, default='', max_length=100, verbose_name='端口类型')),
                ('poe_support', models.BooleanField(blank=True, null=True, verbose_name='是否支持PoE')),
                ('poe_power', models.IntegerField(blank=True, null=True, verbose_name='PoE功率(W)')),
                ('stackable', models.BooleanField(blank=True, null=True, verbose_name='是否可堆叠')),
                ('stack_id', models.CharField(blank=True, default='', max_length=50, verbose_name='堆叠编号')),
                ('redundancy_power', models.BooleanField(blank=True, null=True, verbose_name='是否冗余电源')),
                ('rack_position', models.CharField(blank=True, default='', max_length=100, verbose_name='机架位置')),
                ('software_type', models.CharField(blank=True, choices=[('os', '操作系统'), ('office', '办公软件'), ('database', '数据库'), ('middleware', '中间件'), ('security', '安全软件'), ('design', '设计软件'), ('business', '业务应用'), ('dev_tool', '开发工具'), ('other', '其他')], default='', max_length=20, verbose_name='软件类型')),
                ('version', models.CharField(blank=True, default='', max_length=50, verbose_name='版本号')),
                ('license_type', models.CharField(blank=True, choices=[('perpetual', '永久授权'), ('subscription', '订阅制'), ('opensource', '开源'), ('self_developed', '自研')], default='', max_length=20, verbose_name='授权类型')),
                ('license_key', models.CharField(blank=True, default='', max_length=200, verbose_name='许可证号')),
                ('license_count', models.IntegerField(blank=True, null=True, verbose_name='授权数量')),
                ('used_count', models.IntegerField(blank=True, null=True, verbose_name='已用数量')),
                ('license_expiry', models.DateField(blank=True, null=True, verbose_name='许可到期日期')),
                ('platform', models.CharField(blank=True, default='', max_length=100, verbose_name='运行平台')),
                ('installed_device', models.TextField(blank=True, default='', verbose_name='安装设备')),
                ('consumable_type', models.CharField(blank=True, choices=[('toner', '硒鼓'), ('cartridge', '墨盒'), ('paper', '打印纸'), ('cable', '网线'), ('fiber', '光纤跳线'), ('keyboard_mouse', '键盘鼠标'), ('disc', '光盘'), ('cable_other', '线缆'), ('other', '其他')], default='', max_length=20, verbose_name='耗材类型')),
                ('unit', models.CharField(blank=True, choices=[('piece', '个'), ('box', '箱'), ('pack', '包'), ('roll', '卷'), ('carton', '盒')], default='', max_length=10, verbose_name='单位')),
                ('current_stock', models.IntegerField(blank=True, null=True, verbose_name='当前库存')),
                ('min_stock', models.IntegerField(blank=True, null=True, verbose_name='最低库存预警')),
                ('applicable_device', models.TextField(blank=True, default='', verbose_name='适用设备')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='单价')),
                ('last_purchase_date', models.DateField(blank=True, null=True, verbose_name='上次采购日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='base_data.assetcategory', verbose_name='资产分类')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='base_data.department', verbose_name='使用部门')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='base_data.location', verbose_name='存放位置')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='base_data.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '资产',
                'verbose_name_plural': '资产',
                'db_table': 'asset_asset',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, default='', max_length=20, verbose_name='变更前状态')),
                ('to_status', models.CharField(max_length=20, verbose_name='变更后状态')),
                ('remarks', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='assets.asset', verbose_name='资产')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '状态变更记录',
                'verbose_name_plural': '状态变更记录',
                'db_table': 'asset_status_change',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_type', 'status'], name='asset_asset_asset_t_0602e9_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['department'], name='asset_asset_departm_741a67_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['warranty_expiry'], name='asset_asset_warrant_9cd4c0_idx'),
        ),
    ]
