# Generated by Django 4.2 on 2026-06-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, unique=True, verbose_name='资产编号'),
        ),
    ]
