# Generated by Django 4.2 on 2026-06-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_operationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('server', '服务器'), ('pc', 'PC'), ('printer', '打印机'), ('network_device', '网络设备'), ('switch', '交换机'), ('multimedia', '多媒体设备'), ('software', '软件'), ('consumable', '耗材')], db_index=True, max_length=20, verbose_name='资产类型'),
        ),
    ]
