# Generated by Django 4.2 on 2026-06-12 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(max_length=100, verbose_name='SMTP服务器')),
                ('smtp_port', models.IntegerField(default=587, verbose_name='端口')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('use_tls', models.BooleanField(default=True, verbose_name='使用TLS')),
                ('sender_email', models.CharField(blank=True, default='', max_length=100, verbose_name='发件人邮箱')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='是否启用')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '邮件配置',
                'verbose_name_plural': '邮件配置',
                'db_table': 'alert_email_config',
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('event_type', models.CharField(choices=[('asset_created', '资产新增'), ('status_changed', '资产异动'), ('warranty_expiry', '维保到期'), ('license_expiry', '许可证到期'), ('low_stock', '低库存')], max_length=30, verbose_name='事件类型')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('notify_email', models.BooleanField(default=False, verbose_name='邮件通知')),
                ('notify_system', models.BooleanField(default=True, verbose_name='系统通知')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('notify_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='通知用户')),
            ],
            options={
                'verbose_name': '告警规则',
                'verbose_name_plural': '告警规则',
                'db_table': 'alert_rule',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('message', models.TextField(verbose_name='消息内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_logs', to='assets.asset', verbose_name='关联资产')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='alerts.alertrule', verbose_name='告警规则')),
            ],
            options={
                'verbose_name': '告警日志',
                'verbose_name_plural': '告警日志',
                'db_table': 'alert_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
