# Generated by Django 4.2 on 2026-06-12 03:23

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='位置名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='位置编码')),
                ('location_type', models.CharField(choices=[('server_room', '机房'), ('warehouse', '库房'), ('office', '办公室'), ('other', '其他')], default='warehouse', max_length=20, verbose_name='位置类型')),
                ('address', models.TextField(blank=True, default='', verbose_name='详细地址')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '位置',
                'verbose_name_plural': '位置',
                'db_table': 'base_location',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='供应商名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='供应商编码')),
                ('contact_person', models.CharField(blank=True, default='', max_length=50, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=30, verbose_name='联系电话')),
                ('address', models.TextField(blank=True, default='', verbose_name='地址')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
                'db_table': 'base_supplier',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='部门名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='部门编码')),
                ('manager', models.CharField(blank=True, default='', max_length=50, verbose_name='负责人')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='base_data.department', verbose_name='上级部门')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'db_table': 'base_department',
            },
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='分类编码')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='base_data.assetcategory', verbose_name='上级分类')),
            ],
            options={
                'verbose_name': '资产分类',
                'verbose_name_plural': '资产分类',
                'db_table': 'base_asset_category',
            },
        ),
    ]
