# Generated by Django 4.2 on 2026-06-14 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetFormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('config', models.TextField(default='{}', help_text='JSON: {"sections":[{"name":"区块名","sort_order":1,"fields":[...]}]}', verbose_name='表单配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form_template', to='base_data.assetcategory', verbose_name='资产分类')),
            ],
            options={
                'verbose_name': '表单模板',
                'verbose_name_plural': '表单模板',
                'db_table': 'base_form_template',
            },
        ),
    ]
